<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\*.jpg" />
    <Resource Include="Assets\*.png" />
    <Content Include="..\..\docs\user_dictionary.csv" Link="Assets\user_dictionary.csv" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
